sudo: true
# Use C as a dummy language to avoid Travis-CI setting up a virtualenv
# for us, etc.
language: c
before_install:
  - cat /etc/apt/sources.list
  - ls /etc/apt/sources.list.d
  - dpkg-architecture --list
  - lsb_release -cs
  - lsb_release -is
  # Remove some packages that we get from Debian anyway.
  - sudo apt-get --quiet=2 remove --purge -y mongodb-10gen mysql-client-core-5.5 man-db >/dev/null
  # Remove a problematic and likely unnecessary package.
  - sudo apt-get --quiet=2 remove --purge -y fontconfig >/dev/null
  # Remove some packages that actively depend on locales working properly.
  - sudo apt-get --quiet=2 remove postgresql-9.1 postgresql-contrib-9.1 postgresql-9.2 postgresql-contrib-9.2 postgresql-9.3 postgresql-contrib-9.3 postgresql-9.4 postgresql-contrib-9.4 >/dev/null
  # Tell dpkg it is OK to choose the new config files, without prompting.
  - echo 'Dpkg::Options { "--force-confdef"; "--force-confnew"; }' | sudo dd of=/etc/apt/apt.conf.d/99conf
  - sudo apt-get --quiet=2 update
  - sudo apt-get --quiet=2 upgrade
  - sudo apt-get --quiet=2 --fix-broken install
  # Make sure locales are in a healthy shape.
  - echo 'en_US.UTF-8 UTF-8' | sudo dd of=/etc/locale.gen
  - sudo /usr/sbin/locale-gen
  - sudo apt-get install python-six
  # Install some additional dependencies.
  - sudo apt-get install debootstrap dpkg-dev lsb-release python python-stdeb python-wheel python3 python3-stdeb python3-wheel schroot tox
before_script:
  - export CH_GROUPS="$(id -gn),root"
  - sudo -E ./mkchroot.sh
script:
  - tox
after_script:
  - sudo -E ./rmchroot.sh
